name: Unit test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Checkout sigstore policy controller
        uses: actions/checkout@v4
        with:
          repository: sigstore/policy-controller
          path: policy-controller
      
      - name: Checkout prezha/trustroot
        uses: actions/checkout@v4
        with:
          repository: prezha/trustroot
          path: prezha
          ref: dd9663ae0e6a0e278190b7b93a9c024ec088d104
 
      - name: setup go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0

      - name: install cosign
        uses: sigstore/cosign-installer@v3.8.0

      - name: make policy-controller
        run: cd policy-controller && make policy-tester

      - name: print help
        run: ./policy-controller/policy-tester --help
      
      - name: run prezha/trustroot
        run: cd prezha && bash trustroot.sh https://raw.githubusercontent.com/sigstore/root-signing/refs/heads/main/metadata/root.json https://tuf-repo-cdn.sigstore.dev
      
      - name: cat
        run: cat prezha/TrustRoot.yaml

      # - name: test prezha TrustRoot.yaml
      #   run: |
      #     (set -o pipefail && ./policy-controller/policy-tester \
      #     --policy=tests/testdata/cip-pass-all.yaml \
      #     --image=alpine:latest \
      #     --trustroot=prezha/TrustRoot.yaml | jq) 

      - name: run assembler
        run: go run cmd/main.go --mirror https://tuf-repo-cdn.sigstore.dev > repository.yaml

      - name: cat
        run: cat repository.yaml

      - name: test assembled trustroot
        run: |
          (set -o pipefail && ./policy-controller/policy-tester \
          --policy=tests/testdata/cip-pass-all.yaml \
          --image=alpine:latest \
          --trustroot=repository.yaml | jq)