name: Unit test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Checkout sigstore policy controller
        uses: actions/checkout@v4
        with:
          repository: sigstore/policy-controller
          path: policy-controller
          
      - name: setup go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0

      - name: make policy-controller
        run: cd policy-controller && make policy-tester
